
MODEL:
  META_ARCHITECTURE: Baseline
  PIXEL_MEAN: [127.5, 127.5, 127.5]
  PIXEL_STD: [127.5, 127.5, 127.5]
  USE_QUERY_FEAT: False

  BACKBONE:
    NAME: build_vit_backbone
    DEPTH: base
    FEAT_DIM: 768
    PRETRAIN: True
    PRETRAIN_PATH: /to_path/.cache/torch/checkpoints/jx_vit_base_p16_224-80ecf9dd.pth
    STRIDE_SIZE: (16, 16)
    DROP_PATH_RATIO: 0.1
    DROP_RATIO: 0.0
    ATT_DROP_RATE: 0.0
    INNER_SUB: False
    QUERY_LEN: 64
    QUERY_DEPTH: 2

  HEADS:
    NAME: EmbeddingHead
    NORM: BN
    WITH_BNNECK: True
    POOL_LAYER: Identity
    NECK_FEAT: before
    CLS_LAYER: Linear

  LOSSES:
    NAME: ("CrossEntropyLoss", "TripletLoss",)

    CE:
      EPSILON: 0.
      SCALE: 1.
      # view-related learning
      VIEW_ID: False
      VIEW_OREG: False
      VIEW_LAMBDA: 0.001

    TRI:
      MARGIN: 0.0
      HARD_MINING: True
      NORM_FEAT: False
      SCALE: 1.



INPUT:
  SIZE_TRAIN: [ 256, 128 ]
  SIZE_TEST: [ 256, 128 ]

  REA:
    ENABLED: True
    PROB: 0.5

  FLIP:
    ENABLED: True

  PADDING:
    ENABLED: True

DATALOADER:
  SAMPLER_TRAIN: NaiveIdentitySampler
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  AMP:
    ENABLED: True
  OPT: SGD
  MAX_EPOCH: 120
  BASE_LR: 0.008
  WEIGHT_DECAY: 0.0001
  IMS_PER_BATCH: 128

  SCHED: CosineAnnealingLR
  ETA_MIN_LR: 0.0000016

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 2000

  CLIP_GRADIENTS:
    ENABLED: True

  CHECKPOINT_PERIOD: 5

TEST:
  EVAL_PERIOD: 5
  IMS_PER_BATCH:  384

CUDNN_BENCHMARK: True

DATASETS:
  NAMES: ("AG_ReID_v2",)
  TESTS: ("AG_ReID_v2", "AG_ReID_v2_G2A","AG_ReID_v2_A2W","AG_ReID_v2_W2A")
  # TESTS: ("AG_ReID_v2")

OUTPUT_DIR: logs/AG_ReID_v2/ViT_base
